services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=library'
      - 'MYSQL_ROOT_PASSWORD=@Kel851762'
    ports:
      - '3307:3306'
  redis:
    image: redis
    ports:
      - "6379:6379"